### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by sassyn** [crackofdusk/glitchy-space#3]
Hi,

I have tested our project on my IOS 6 Phone and I can't hear the audio.

It was working on my MacBook with safari.

Can you please verify if it should work on `IOS?

I wanted to see a project that use the Aurora.js framework under IOS

Thank You

**Comment by crackofdusk** [comment]
The audio does not work on mobile devices. Mobile browsers (at least Chrome and Safari as far I know) restrict how sound or video can be loaded. I didn't try workarounds, because this is just a demo. Besides, the visualization part is already slow on mobile, adding software decoding of audio won't help.
